CREATE TABLE SALES
(
    PRODUCT_GROUP   VARCHAR(50),
    ITEM            VARCHAR(50),
    SOLD            DATE,
    UNITS           INT,
    PRICE           DECIMAL(12,2) 
);

INSERT INTO SALES (PRODUCT_GROUP, ITEM, SOLD, UNITS, PRICE) 
VALUES 
('Accessories', 'Bag', TO_DATE('2016-09-01', 'YYYY-MM-DD'), 1, 1.00),
('Accessories', 'Cable', TO_DATE('2016-09-02', 'YYYY-MM-DD'), 4, 5.00),
('Accessories', 'Smartphone Case', TO_DATE('2016-09-03', 'YYYY-MM-DD'), 20, 15.00),
('Electronics', 'Smartphone', TO_DATE('2016-09-04', 'YYYY-MM-DD'), 8, 500.00),
('Electronics', 'Tablet', TO_DATE('2016-09-05', 'YYYY-MM-DD'), 40, 1250.00),
('Electronics', 'Workstation', TO_DATE('2016-09-06', 'YYYY-MM-DD'), 300, 2000.00),
('Accessories', 'Bag', TO_DATE('2016-10-01', 'YYYY-MM-DD'), 1, 1.00),
('Accessories', 'Cable', TO_DATE('2016-10-02', 'YYYY-MM-DD'), 1, 5.00),
('Accessories', 'Cable', TO_DATE('2016-10-03', 'YYYY-MM-DD'), 2, 5.00),
('Accessories', 'Cable', TO_DATE('2016-10-04', 'YYYY-MM-DD'), 1, 5.00),
('Accessories', 'Smartphone Case', TO_DATE('2016-10-05', 'YYYY-MM-DD'), 2, 15.00),
('Accessories', 'Smartphone Case', TO_DATE('2016-10-06', 'YYYY-MM-DD'), 4, 15.00),
('Accessories', 'Smartphone Case', TO_DATE('2016-10-07', 'YYYY-MM-DD'), 4, 15.00),
('Accessories', 'Smartphone Case', TO_DATE('2016-10-08', 'YYYY-MM-DD'), 5, 15.00),
('Accessories', 'Smartphone Case', TO_DATE('2016-10-09', 'YYYY-MM-DD'), 3, 15.00),
('Accessories', 'Smartphone Case', TO_DATE('2016-10-10', 'YYYY-MM-DD'), 2, 15.00),
('Electronics', 'Smartphone', TO_DATE('2016-10-11', 'YYYY-MM-DD'), 2, 500.00),
('Electronics', 'Smartphone', TO_DATE('2016-10-12', 'YYYY-MM-DD'), 1, 500.00),
('Electronics', 'Smartphone', TO_DATE('2016-10-13', 'YYYY-MM-DD'), 3, 500.00),
('Electronics', 'Smartphone', TO_DATE('2016-10-14', 'YYYY-MM-DD'), 2, 500.00),
('Electronics', 'Tablet', TO_DATE('2016-10-15', 'YYYY-MM-DD'), 10, 1250.00),
('Electronics', 'Tablet', TO_DATE('2016-10-16', 'YYYY-MM-DD'), 15, 1250.00),
('Electronics', 'Tablet', TO_DATE('2016-10-17', 'YYYY-MM-DD'), 5, 1250.00),
('Electronics', 'Tablet', TO_DATE('2016-10-18', 'YYYY-MM-DD'), 10, 1250.00),
('Electronics', 'Workstation', TO_DATE('2016-10-19', 'YYYY-MM-DD'), 10, 2000.00),
('Electronics', 'Workstation', TO_DATE('2016-10-20', 'YYYY-MM-DD'), 90, 2000.00),
('Electronics', 'Workstation', TO_DATE('2016-10-21', 'YYYY-MM-DD'), 25, 2000.00),
('Electronics', 'Workstation', TO_DATE('2016-10-22', 'YYYY-MM-DD'), 50, 2000.00);


CREATE EXTENSION IF NOT EXISTS tablefunc;
CREATE TABLE olympic_medal_winners (
  olympic_year INT,
  sport        VARCHAR(30),
  gender       VARCHAR(1),
  event        VARCHAR(128),
  medal        VARCHAR(10),
  noc          VARCHAR(3),
  athlete      VARCHAR(128)
);

INSERT INTO olympic_medal_winners (OLYMPIC_YEAR,SPORT,GENDER,EVENT,MEDAL,NOC,ATHLETE)
VALUES
(2016,'Wrestling','M','Men''s Freestyle 57 kg','Bronze','AZE','ALIYEV Haji'),
(2016,'Archery','M','Men''s Individual','Gold','KOR','KU Bonchan'),
(2016,'Archery','M','Men''s Individual','Silver','FRA','VALLADONT Jean-Charles'),
(2016,'Archery','M','Men''s Individual','Bronze','USA','ELLISON Brady'),
(2016,'Archery','M','Men''s Team','Gold','KOR','Republic of Korea'),
(2016,'Archery','M','Men''s Team','Bronze','AUS','Australia'),
(2016,'Archery','M','Men''s Team','Silver','USA','United States'),
(2016,'Artistic Gymnastics','M','Men''s Floor Exercise','Gold','GBR','WHITLOCK Max'),
(2016,'Artistic Gymnastics','M','Men''s Floor Exercise','Bronze','BRA','MARIANO Arthur'),
(2016,'Artistic Gymnastics','M','Men''s Floor Exercise','Silver','BRA','HYPOLITO Diego'),
(2016,'Artistic Gymnastics','M','Men''s Horizontal Bar','Gold','GER','HAMBUECHEN Fabian'),
(2016,'Artistic Gymnastics','M','Men''s Horizontal Bar','Bronze','GBR','WILSON Nile'),
(2016,'Artistic Gymnastics','M','Men''s Horizontal Bar','Silver','USA','LEYVA Danell'),
(2016,'Athletics','M','Men''s 10,000m','Gold','GBR','FARAH Mohamed'),
(2016,'Athletics','M','Men''s 10,000m','Bronze','ETH','TOLA Tamirat'),
(2016,'Athletics','M','Men''s 10,000m','Silver','KEN','TANUI Paul Kipngetich'),
(2016,'Athletics','M','Men''s 100m','Gold','JAM','BOLT Usain'),
(2016,'Athletics','M','Men''s 100m','Silver','USA','GATLIN Justin'),
(2016,'Athletics','M','Men''s 100m','Bronze','CAN','DE GRASSE Andre'),
(2016,'Badminton','M','Men''s Doubles','Gold','CHN','Zhang'),
(2016,'Badminton','M','Men''s Doubles','Bronze','GBR','Langridge'),
(2016,'Badminton','M','Men''s Doubles','Bronze','GBR','Ellis'),
(2016,'Badminton','M','Men''s Doubles','Silver','MAS','Tan'),
(2016,'Badminton','M','Men''s Doubles','Silver','MAS','Goh'),
(2016,'Badminton','M','Men''s Doubles','Gold','CHN','Fu'),
(2016,'Beach Volleyball','M','Men','Gold','BRA','Cerutti'),
(2016,'Beach Volleyball','M','Men','Gold','BRA','Oscar Schmidt'),
(2016,'Beach Volleyball','M','Men','Silver','ITA','Nicolai'),
(2016,'Beach Volleyball','M','Men','Silver','ITA','Lupo'),
(2016,'Beach Volleyball','M','Men','Bronze','NED','Meeuwsen'),
(2016,'Beach Volleyball','M','Men','Bronze','NED','Brouwer'),
(2016,'Boxing','M','Men''s Bantam (56kg)','Gold','CUB','RAMIREZ Robeisy'),
(2016,'Boxing','M','Men''s Bantam (56kg)','Bronze','UZB','AKHMADALIEV Murodjon'),
(2016,'Boxing','M','Men''s Bantam (56kg)','Bronze','RUS','NIKITIN Vladimir'),
(2016,'Boxing','M','Men''s Bantam (56kg)','Silver','USA','STEVENSON Shakur'),
(2016,'Boxing','M','Men''s Fly (52kg)','Gold','UZB','ZOIROV Shakhobidin'),
(2016,'Boxing','M','Men''s Fly (52kg)','Bronze','CHN','HU Jianguan'),
(2016,'Canoe Slalom','M','Canoe Double (C2) Men','Gold','SVK','PETER Skantar'),
(2016,'Canoe Slalom','M','Canoe Double (C2) Men','Bronze','FRA','GAUTHIER Klauss'),
(2016,'Canoe Slalom','M','Canoe Double (C2) Men','Bronze','FRA','MATTHIEU Peche'),
(2016,'Canoe Slalom','M','Canoe Double (C2) Men','Silver','GBR','RICHARD Hounslow'),
(2016,'Canoe Slalom','M','Canoe Double (C2) Men','Silver','GBR','DAVID Florence'),
(2016,'Canoe Slalom','M','Canoe Double (C2) Men','Gold','SVK','LADISLAV Skantar'),
(2016,'Canoe Sprint','M','Men''s Canoe Double 1000m','Gold','GER','Brendel'),
(2016,'Canoe Sprint','M','Men''s Canoe Double 1000m','Bronze','UKR','Mishchuk'),
(2016,'Canoe Sprint','M','Men''s Canoe Double 1000m','Bronze','UKR','Ianchuk'),
(2016,'Canoe Sprint','M','Men''s Canoe Double 1000m','Silver','BRA','Queiroz dos Santos'),
(2016,'Canoe Sprint','M','Men''s Canoe Double 1000m','Silver','BRA','de Souza Silva'),
(2016,'Canoe Sprint','M','Men''s Canoe Double 1000m','Gold','GER','Vandrey'),
(2016,'Cycling Road','M','Men''s Individual Time Trial','Gold','SUI','CANCELLARA Fabian'),
(2016,'Cycling Road','M','Men''s Individual Time Trial','Bronze','GBR','FROOME Christopher'),
(2016,'Cycling Road','M','Men''s Individual Time Trial','Silver','NED','DUMOULIN Tom'),
(2016,'Cycling Road','M','Men''s Road Race','Gold','BEL','VAN AVERMAET Greg'),
(2016,'Cycling Road','M','Men''s Road Race','Silver','DEN','FUGLSANG Jakob'),
(2016,'Cycling Road','M','Men''s Road Race','Bronze','POL','MAJKA Rafal'),
(2016,'Cycling Track','M','Men''s Keirin','Gold','GBR','KENNY Jason'),
(2016,'Cycling Track','M','Men''s Keirin','Bronze','MAS','AWANG Azizulhasni'),
(2016,'Cycling Track','M','Men''s Keirin','Silver','NED','BUCHLI Matthijs'),
(2016,'Cycling Track','M','Men''s Omnium','Gold','ITA','VIVIANI Elia'),
(2016,'Cycling Track','M','Men''s Omnium','Bronze','DEN','HANSEN Lasse Norman'),
(2016,'Cycling Track','M','Men''s Omnium','Silver','GBR','CAVENDISH Mark'),
(2016,'Diving','M','Men''s 10m Platform','Gold','CHN','CHEN Aisen'),
(2016,'Diving','M','Men''s 10m Platform','Bronze','USA','BOUDIA David'),
(2016,'Diving','M','Men''s 10m Platform','Silver','MEX','SANCHEZ German'),
(2016,'Diving','M','Men''s 3m Springboard','Gold','CHN','CAO Yuan'),
(2016,'Diving','M','Men''s 3m Springboard','Silver','GBR','LAUGHER Jack'),
(2016,'Diving','M','Men''s 3m Springboard','Bronze','GER','HAUSDING Patrick'),
(2016,'Equestrian','X','Dressage Individual','Gold','GBR','DUJARDIN Charlotte'),
(2016,'Equestrian','X','Dressage Individual','Bronze','GER','BRORING-SPREHE Kristina'),
(2016,'Equestrian','X','Dressage Individual','Silver','GER','WERTH Isabell'),
(2016,'Equestrian','X','Dressage Team','Gold','GER','Germany'),
(2016,'Equestrian','X','Dressage Team','Bronze','USA','United States'),
(2016,'Equestrian','X','Dressage Team','Silver','GBR','Great Britain'),
(2016,'Fencing','M','Men''s Foil Individual','Gold','ITA','GAROZZO Daniele'),
(2016,'Fencing','M','Men''s Foil Individual','Silver','USA','MASSIALAS Alexander'),
(2016,'Fencing','M','Men''s Foil Individual','Bronze','RUS','SAFIN Timur'),
(2016,'Fencing','M','Men''s Foil Team','Gold','RUS','Russian Federation'),
(2016,'Fencing','M','Men''s Foil Team','Bronze','USA','United States'),
(2016,'Fencing','M','Men''s Foil Team','Silver','FRA','France'),
(2016,'Handball','M','Men','Gold','DEN','Denmark'),
(2016,'Handball','M','Men','Silver','FRA','France'),
(2016,'Handball','M','Men','Bronze','GER','Germany'),
(2016,'Handball','W','Women','Gold','RUS','Russian Federation'),
(2016,'Handball','W','Women','Silver','FRA','France'),
(2016,'Handball','W','Women','Bronze','NOR','Norway'),
(2016,'Hockey','M','Men','Gold','ARG','Argentina'),
(2016,'Hockey','M','Men','Silver','BEL','Belgium'),
(2016,'Hockey','M','Men','Bronze','GER','Germany'),
(2016,'Hockey','W','Women','Gold','GBR','Great Britain'),
(2016,'Hockey','W','Women','Silver','NED','Netherlands'),
(2016,'Hockey','W','Women','Bronze','GER','Germany'),
(2016,'Judo','M','Men +100 kg','Gold','FRA','RINER Teddy'),
(2016,'Judo','M','Men +100 kg','Bronze','BRA','SILVA Rafael'),
(2016,'Judo','M','Men +100 kg','Bronze','ISR','SASSON Or'),
(2016,'Judo','M','Men +100 kg','Silver','JPN','HARASAWA Hisayoshi'),
(2016,'Judo','M','Men -100 kg','Gold','CZE','KRPALEK Lukas'),
(2016,'Judo','M','Men -100 kg','Bronze','FRA','MARET Cyrille'),
(2016,'Modern Pentathlon','M','Men''s Individual','Gold','RUS','LESUN Alexander'),
(2016,'Modern Pentathlon','M','Men''s Individual','Silver','UKR','TYMOSHCHENKO Pavlo'),
(2016,'Modern Pentathlon','M','Men''s Individual','Bronze','MEX','HERNANDEZ USCANGA Ismael Marcelo'),
(2016,'Modern Pentathlon','W','Women''s Individual','Gold','AUS','ESPOSITO Chloe'),
(2016,'Modern Pentathlon','W','Women''s Individual','Silver','FRA','CLOUVEL Elodie'),
(2016,'Modern Pentathlon','W','Women''s Individual','Bronze','POL','NOWACKA Oktawia'),
(2016,'Rhythmic Gymnastics','W','Group All-Around','Gold','RUS','Russian Federation'),
(2016,'Rhythmic Gymnastics','W','Group All-Around','Bronze','BUL','Bulgaria'),
(2016,'Rhythmic Gymnastics','W','Group All-Around','Silver','ESP','Spain'),
(2016,'Rhythmic Gymnastics','W','Individual All-Around','Gold','RUS','MAMUN Margarita'),
(2016,'Rhythmic Gymnastics','W','Individual All-Around','Silver','RUS','KUDRYAVTSEVA Yana'),
(2016,'Rhythmic Gymnastics','W','Individual All-Around','Bronze','UKR','RIZATDINOVA Ganna'),
(2016,'Rowing','M','Lightweight Men''s Double Sculls','Gold','FRA','Azou'),
(2016,'Rowing','M','Lightweight Men''s Double Sculls','Bronze','NOR','Brun'),
(2016,'Rowing','M','Lightweight Men''s Double Sculls','Bronze','NOR','Strandli'),
(2016,'Rowing','M','Lightweight Men''s Double Sculls','Silver','IRL','O''Donovan'),
(2016,'Rowing','M','Lightweight Men''s Double Sculls','Silver','IRL','O''Donovan'),
(2016,'Rowing','M','Lightweight Men''s Double Sculls','Gold','FRA','Houin'),
(2016,'Sailing','M','470 Men','Gold','CRO','Fantela'),
(2016,'Sailing','M','470 Men','Bronze','GRE','Kagialis'),
(2016,'Sailing','M','470 Men','Bronze','GRE','Mantis'),
(2016,'Sailing','M','470 Men','Silver','AUS','Ryan'),
(2016,'Sailing','M','470 Men','Silver','AUS','Belcher'),
(2016,'Sailing','M','470 Men','Gold','CRO','Marenic'),
(2016,'Swimming','M','Men''s 100m Backstroke','Gold','USA','MURPHY Ryan'),
(2016,'Swimming','M','Men''s 100m Backstroke','Bronze','USA','PLUMMER David'),
(2016,'Swimming','M','Men''s 100m Backstroke','Silver','CHN','XU Jiayu'),
(2016,'Swimming','M','Men''s 100m Breaststroke','Gold','GBR','PEATY Adam'),
(2016,'Swimming','M','Men''s 100m Breaststroke','Bronze','USA','MILLER Cody'),
(2016,'Swimming','M','Men''s 100m Breaststroke','Silver','RSA','VAN DER BURGH Cameron'),
(2016,'Table Tennis','M','Men''s Singles','Gold','CHN','MA Long'),
(2016,'Table Tennis','M','Men''s Singles','Bronze','JPN','MIZUTANI Jun'),
(2016,'Table Tennis','M','Men''s Singles','Silver','CHN','ZHANG Jike'),
(2016,'Table Tennis','M','Men''s Team','Gold','CHN','China'),
(2016,'Table Tennis','M','Men''s Team','Bronze','GER','Germany'),
(2016,'Table Tennis','M','Men''s Team','Silver','JPN','Japan'),
(2016,'Taekwondo','M','Men +80kg','Gold','AZE','ISAEV Radik'),
(2016,'Taekwondo','M','Men +80kg','Bronze','KOR','CHA Dongmin'),
(2016,'Taekwondo','M','Men +80kg','Bronze','BRA','SIQUEIRA Maicon'),
(2016,'Taekwondo','M','Men +80kg','Silver','NIG','ISSOUFOU ALFAGA Abdoulrazak'),
(2016,'Taekwondo','M','Men -58kg','Gold','CHN','ZHAO Shuai'),
(2016,'Taekwondo','M','Men -58kg','Silver','THA','HANPRAB Tawin'),
(2016,'Tennis','M','Men''s Doubles','Gold','ESP','Lopez'),
(2016,'Tennis','M','Men''s Doubles','Bronze','USA','Johnson'),
(2016,'Tennis','M','Men''s Doubles','Bronze','USA','Sock'),
(2016,'Tennis','M','Men''s Doubles','Silver','ROU','Tecau'),
(2016,'Tennis','M','Men''s Doubles','Silver','ROU','Mergea'),
(2016,'Tennis','M','Men''s Doubles','Gold','ESP','Nadal'),
(2016,'Trampoline Gymnastics','M','Men','Gold','BLR','HANCHAROU Uladzislau'),
(2016,'Trampoline Gymnastics','M','Men','Silver','CHN','DONG Dong'),
(2016,'Trampoline Gymnastics','M','Men','Bronze','CHN','GAO Lei'),
(2016,'Trampoline Gymnastics','W','Women','Gold','CAN','MACLENNAN Rosannagh'),
(2016,'Trampoline Gymnastics','W','Women','Silver','GBR','PAGE Bryony'),
(2016,'Trampoline Gymnastics','W','Women','Bronze','CHN','LI Dan'),
(2016,'Triathlon','M','Men','Gold','GBR','BROWNLEE Alistair'),
(2016,'Triathlon','M','Men','Silver','GBR','BROWNLEE Jonathan'),
(2016,'Triathlon','M','Men','Bronze','RSA','SCHOEMAN Henri'),
(2016,'Triathlon','W','Women','Gold','USA','JORGENSEN Gwen'),
(2016,'Triathlon','W','Women','Silver','SUI','SPIRIG HUG Nicola'),
(2016,'Triathlon','W','Women','Bronze','GBR','HOLLAND Vicky'),
(2016,'Volleyball','M','Men','Gold','BRA','Brazil'),
(2016,'Volleyball','M','Men','Silver','ITA','Italy'),
(2016,'Volleyball','M','Men','Bronze','USA','United States'),
(2016,'Volleyball','W','Women','Gold','CHN','China'),
(2016,'Volleyball','W','Women','Silver','SRB','Serbia'),
(2016,'Volleyball','W','Women','Bronze','USA','United States'),
(2016,'Water Polo','M','Men','Gold','SRB','Serbia'),
(2016,'Water Polo','M','Men','Silver','CRO','Croatia'),
(2016,'Water Polo','M','Men','Bronze','ITA','Italy'),
(2016,'Water Polo','W','Women','Gold','USA','United States'),
(2016,'Water Polo','W','Women','Silver','ITA','Italy'),
(2016,'Water Polo','W','Women','Bronze','RUS','Russian Federation'),
(2016,'Weightlifting','M','Men''s +105kg','Gold','GEO','TALAKHADZE Lasha'),
(2016,'Weightlifting','M','Men''s +105kg','Bronze','GEO','TURMANIDZE Irakli'),
(2016,'Weightlifting','M','Men''s +105kg','Silver','ARM','MINASYAN Gor'),
(2016,'Weightlifting','M','Men''s 105kg','Gold','UZB','NURUDINOV Ruslan'),
(2016,'Weightlifting','M','Men''s 105kg','Bronze','KAZ','ZAICHIKOV Alexandr'),
(2016,'Weightlifting','M','Men''s 105kg','Silver','ARM','MARTIROSYAN Simon'),
(2016,'Wrestling','M','Men''s Freestyle 125 kg','Gold','TUR','AKGUL Taha'),
(2016,'Wrestling','M','Men''s Freestyle 125 kg','Bronze','BLR','SAIDAU Ibrahim'),
(2016,'Wrestling','M','Men''s Freestyle 125 kg','Bronze','GEO','PETRIASHVILI Geno'),
(2016,'Wrestling','M','Men''s Freestyle 125 kg','Silver','IRI','GHASEMI Komeil Nemat'),
(2016,'Wrestling','M','Men''s Freestyle 57 kg','Gold','GEO','KHINCHEGASHVILI Vladimer');